/*
 * Nchf_spendinglimitcontrol
 *
 * Spending Limit Control
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// SpendingLimitStatus 3GPP TS 29 594 Section 5.6.2.3
type SpendingLimitStatus struct {
	Supi string `json:"supi" yaml:"supi" bson:"supi" mapstructure:"Supi"`
	// A map, keyed by policyCounterId, of the status of the requested policy counters.
	StatusInfos       map[string]PolicyCounterInfo `json:"statusInfos,omitempty" yaml:"statusInfos" bson:"statusInfos" mapstructure:"StatusInfos"`
	SupportedFeatures string                       `json:"supportedFeatures,omitempty" yaml:"supportedFeatures" bson:"supportedFeatures" mapstructure:"SupportedFeatures"`
}
