/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ServingNetworkFunctionID TS 132 291 Section 6.1.6.2.2.12
type ServingNFID struct {
	servingNetworkFunctionInformation NFConsumerIdentification `json:"servingNetworkFunctionInformation" yaml:"servingNetworkFunctionInformation" bson:"servingNetworkFunctionInformation" mapstructure:"ServingNetworkFunctionInformation"`
	aMFId                             string                   `json:"aMFId" yaml:"aMFId" bson:"aMFId" mapstructure:"AMFId"`
}
