/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ChargingDataEventType TS 132 291 Section  6.1.6.3.28
type ChargingDataEventType string

//  List of ChargingDataEventType
const (
	ChargingDataEventType__IEC ChargingDataEventType = "IEC"
	ChargingDataEventType__PEC ChargingDataEventType = "PEC"
)
