/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "time"

// PDUSessionChargingInformation TS 132 291 Section 6.1.6.2.2.6
type PduSessionChargingInformation struct {
	ChargingId                       uint32                  `json:"chargingId" yaml:"chargingId" bson:"chargingId" mapstructure:"ChargingId"`
	UserInformation                  UserInformation         `json:"userInformation" yaml:"userInformation" bson:"userInformation" mapstructure:"UserInformation"`
	UserLocationinfo                 UserLocation            `json:"userLocationinfo" yaml:"userLocationinfo" bson:"userLocationinfo" mapstructure:"UserLocationinfo"`
	UserLocationTime                 *time.Time              `json:"userLocationTime" yaml:"userLocationTime" bson:"userLocationTime" mapstructure:"UserLocationTime"`
	PresenceReportingAreaInformation []PresenceInfo          `json:"presenceReportingAreaInformation" yaml:"presenceReportingAreaInformation" bson:"presenceReportingAreaInformation" mapstructure:"PresenceReportingAreaInformation"`
	UeTimeZone                       string                  `json:"ueTimeZone" yaml:"ueTimeZone" bson:"UeTimeZone" mapstructure:"UeTimeZone"`
	PduSessionInformation            PduSessionInformation   `json:"pduSessionInformation" yaml:"pduSessionInformation" bson:"pduSessionInformation" mapstructure:"PduSessionInformation"`
	UnitCountInactivityTimer         uint                    `json:"unitCountInactivityTimer" yaml:"unitCountInactivityTimer" bson:"unitCountInactivityTimer" mapstructure:"UnitCountInactivityTimer"`
	RANSecondaryRATUsageReport       SecondaryRatUsageReport `json:"rANSecondaryRATUsageReport" yaml:"rANSecondaryRATUsageReport" bson:"rANSecondaryRATUsageReport" mapstructure:"RANSecondaryRATUsageReport"`
}
