/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ChargingDataResponse TS 132 291 Section 6.1.6.3.12
type SessionFailover string

// List of SessionFailover
const (
	SessionFailover_FAILOVER_NOT_SUPPORTED SessionFailover = "FAILOVER_NOT_SUPPORTED"
	SessionFailover_FAILOVER_SUPPORTED     SessionFailover = "FAILOVER_SUPPORTED"
)
