/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ChargingCharacteristicsSelectionMode TS 132 291 Section  6.1.6.3.5
type ChargingCharacteristicsSelectionMode string

//  List of ChargingCharacteristicsSelectionMode
const (
	ChargingCharacteristicsSelectionMode__HOME_DEFAULT     ChargingCharacteristicsSelectionMode = "HOME_DEFAULT"
	ChargingCharacteristicsSelectionMode__ROAMING_DEFAULT  ChargingCharacteristicsSelectionMode = "ROAMING_DEFAULT"
	ChargingCharacteristicsSelectionMode__VISITING_DEFAULT ChargingCharacteristicsSelectionMode = "VISITING_DEFAULT"
)
