/*
 * Nchf_spendinglimitcontrol
 *
 * Spending Limit Control
 *
 * API version: 1.0.1
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// PolicyCounterInfo 3GPP TS 29 594 Section 5.6.2.4
type PolicyCounterInfo struct {
	PolicyCounterId       string                         `json:"policyCounterId" yaml:"policyCounterId" bson:"policyCounterId" mapstructure:"PolicyCounterId"`
	CurrentStatus         string                         `json:"currentStatus" yaml:"currentStatus" bson:"currentStatus" mapstructure:"CurrentStatus"`
	PenPolCounterStatuses map[string]PenPolCounterStatus `json:"penPolCounterStatuses" yaml:"penPolCounterStatuses" bson:"penPolCounterStatuses" mapstructure:"penPolCounterStatuses"`
}
