/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// RoamerInOut TS 132 291 Section  6.1.6.3.16
type RoamerInOut string

//  List of RoamerInOut
const (
	RoamerInOut__IN_BOUND  RoamerInOut = "IN_BOUND"
	RoamerInOut__OUT_BOUND RoamerInOut = "OUT_BOUND"
)
