/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// NFConsumerIdentification TS 132 291 Section  6.1.6.2.1.4
type NFConsumerIdentification struct {
	NodeFunctionality NodeFunctionality `json:"nodeFunctionality" yaml:"nodeFunctionality" bson:"nodeFunctionality" mapstructure:"yaml"`
	NfName            string            `json:"nFName" yaml:"nFName" bson:"nFName" mapstructure:"NFName"`
	NfIpv4Address     string            `json:"nFIPv4Address" yaml:"NFIPv4Address" bson:"nFIPv4Address" mapstructure:"NFIPv4Address"`
	NfIpv6Addres      string            `json:"nFIPv6Addres" yaml:"nFIPv6Addres" bson:"nFIPv6Addres" mapstructure:"NFIPv6Addres"`
	NfFqdn            string            `json:"nFFqdn" yaml:"nFFqdn" bson:"nFFqdn" mapstructure:"NFFqdn"`
	NfPlmnID          PlmnId            `json:"nFPLMNID" yaml:"nFPLMNID" bson:"nFPLMNID" mapstructure:"NFPLMNID"`
}
