/*
 * Nsmf_PDUSession
 *
 * SMF PDU Session Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

type Trigger struct {
	TriggerType     TriggerType     `json:"triggerType"`
	TriggerCategory TriggerCategory `json:"triggerCategory"`
	TimeLimit       int32           `json:"timeLimit,omitempty"`
	VolumeLimit     uint32          `json:"volumeLimit,omitempty"`
	VolumeLimit64   uint64          `json:"volumeLimit64,omitempty"`
	MaxNumberOfccc  uint32          `json:"maxNumberOfccc,omitempty"`
}
