/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// 3GPPPSDataOffStatus TS 132 291 Section  6.1.6.3.13
type Var3GPPPSDataOffStatus string

//  List of 3GPPPSDataOffStatus
const (
	Var3GPPPSDataOffStatus__ACTIVE   Var3GPPPSDataOffStatus = "ACTIVE"
	Var3GPPPSDataOffStatus__INACTIVE Var3GPPPSDataOffStatus = "INACTIVE"
)
