/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "time"

// RequestedUnit 3GPP TS 32 291 Table 6.1.6.2.1.9
type RequestedUnit struct {
	Time                 *time.Time `json:"time" yaml:"time" bson:"time" mapstructure:"Time"`
	TotalVolume          uint64     `json:"totalVolume,omitempty" yaml:"totalVolume" bson:"totalVolume" mapstructure:"TotalVolume"`
	UplinkVolume         uint64     `json:"uplinkVolume" yaml:"uplinkVolume" bson:"uplinkVolume" mapstructure:"UplinkVolume"`
	DownlinkVolume       uint64     `json:"downlinkVolume" yaml:"downlinkVolume" bson:"downlinkVolume" mapstructure:"DownlinkVolume"`
	ServiceSpecificUnits uint64     `json:"serviceSpecificUnits" yaml:"serviceSpecificUnits" bson:"serviceSpecificUnits" mapstructure:"ServiceSpecificUnits"`
}
