/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// NodeFunctionality TS 132 291 Section  6.1.6.3.4
type NodeFunctionality string

//  List of NodeFunctionality
const (
	NodeFunctionality__SMF  NodeFunctionality = "SMF"
	NodeFunctionality__AMF  NodeFunctionality = "AMF"
	NodeFunctionality__SMSF NodeFunctionality = "SMSF"
)
