/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// QuotaManagementIndicator TS 132 291 Section  6.1.6.3.10
type QuotaManagementIndicator string

//  List of QuotaManagementIndicator
const (
	QuotaManagementIndicator__ONLINE_CHARGING  QuotaManagementIndicator = "ONLINE_CHARGING"
	QuotaManagementIndicator__OFFLINE_CHARGING QuotaManagementIndicator = "OFFLINE_CHARGING"
)
