/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "time"

// UsedUnitContainer 3GPP TS 32 291 Table 6.1.6.2.1.10
type UsedUnitContainer struct {
	ServiceId                uint32                     `json:"serviceId" yaml:"serviceId" bson:"serviceId" mapstructure:"ServiceId"`
	QuotaManagementIndicator []QuotaManagementIndicator `json:"quotaManagementIndicator" yaml:"quotaManagementIndicator" bson:"quotaManagementIndicator" mapstructure:"QuotaManagementIndicator"`
	Triggers                 Trigger                    `json:"triggers" yaml:"triggers" bson:"triggers" mapstructure:"Triggers"`
	TriggerTimestamp         *time.Time                 `json:"triggerTimestamp" yaml:"triggerTimestamp" bson:"triggerTimestamp" mapstructure:"TriggerTimestamp"`
	Time                     uint32                     `json:"time" yaml:"time" bson:"time" mapstructure:"Time"`
	TotalVolume              uint64                     `json:"totalVolume" yaml:"totalVolume" bson:"totalVolume" mapstructure:"TotalVolume"`
	UplinkVolume             uint64                     `json:"uplinkVolume" yaml:"uplinkVolume" bson:"uplinkVolume" mapstructure:"UplinkVolume"`
	DownlinkVolume           uint64                     `json:"downlinkVolume" yaml:"downlinkVolume" bson:"downlinkVolume" mapstructure:"DownlinkVolume"`
	ServiceSpecificUnits     uint64                     `json:"serviceSpecificUnits" yaml:"serviceSpecificUnits" bson:"serviceSpecificUnits" mapstructure:"ServiceSpecificUnits"`
	EventTimeStamps          *time.Time                 `json:"eventTimeStamps" yaml:"eventTimeStamps" bson:"eventTimeStamps" mapstructure:"EventTimeStamps"`
	LocalSequenceNumber      int                        `json:"localSequenceNumber" yaml:"localSequenceNumber" bson:"localSequenceNumber" mapstructure:"LocalSequenceNumber"`
}
