/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

import "time"

// QFIContainerInformation TS 132 291 Section 6.1.6.2.2.16
type QFIContainerInformation struct {
	QFI                              int32                  `json:"qFI" yaml:"qFI" bson:"qFI" mapstructure:"QFI"`
	ReportTime                       *time.Time             `json:"reportTime" yaml:"reportTime" bson:"reportTime" mapstructure:"ReportTime"`
	TimeofFirstUsage                 *time.Time             `json:"timeofFirstUsage" yaml:"timeofFirstUsage" bson:"timeofFirstUsage" mapstructure:"TimeofFirstUsage"`
	TimeofLastUsage                  *time.Time             `json:"timeofLastUsage" yaml:"timeofLastUsage" bson:"timeofLastUsage" mapstructure:"TimeofLastUsage"`
	QoSInformation                   QosData                `json:"qoSInformation" yaml:"qoSInformation" bson:"qoSInformation" mapstructure:"QoSInformation"`
	UserLocationInformation          UserLocation           `json:"userLocationInformation" yaml:"userLocationInformation" bson:"userLocationInformation" mapstructure:"UserLocationInformation"`
	UetimeZone                       string                 `json:"uetimeZone" yaml:"uetimeZone" bson:"uetimeZone" mapstructure:"UetimeZone"`
	PresenceReportingAreaInformation PresenceInfo           `json:"presenceReportingAreaInformation" yaml:"presenceReportingAreaInformation" bson:"presenceReportingAreaInformation" mapstructure:"PresenceReportingAreaInformation"`
	RATType                          []RatType              `json:"rATType" yaml:"rATType" bson:"rATType" mapstructure:"RATType"`
	ServingNetworkFunctionID         ServingNFID            `json:"servingNetworkFunctionID" yaml:"servingNetworkFunctionID" bson:"servingNetworkFunctionID" mapstructure:"ServingNetworkFunctionID"`
	Var3gppPSDataOffStatus           Var3GPPPSDataOffStatus `json:"3gppPSDataOffStatus" yaml:"3gppPSDataOffStatus" bson:"3gppPSDataOffStatus" mapstructure:"3gppPSDataOffStatus"`
}
