/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ChargingDataResponse TS 132 291 Section 6.1.6.2.2.2
type ChargingDataResponse struct {
	PDUSessionChargingInformation PduSessionChargingInformation `json:"pDUSessionChargingInformation" yaml:"pDUSessionChargingInformation" bson:"pDUSessionChargingInformation" mapstructure:"PDUSessionChargingInformation"`
	RoamingQBCInformation         RoamingQBCInformation         `json:"roamingQBCInformation" yaml:"roamingQBCInformation" bson:"roamingQBCInformation" mapstructure:"RoamingQBCInformation"`
}
