/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// ChargingDataResponse TS 132 291 Section 6.1.6.3.11-1
type FailureHandling string

// List of FailureHandling
const (
	FailureHandling_TERMINATE           FailureHandling = "TERMINATE"
	FailureHandling_CONTINUE            FailureHandling = "CONTINUE"
	FailureHandling_RETRY_AND_TERMINATE FailureHandling = "RETRY_AND_TERMINATE"
)
