/*
 * Nchf_ConvergedCharging
 *
 * Charging Function Service API
 *
 * API version 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package models

// UserInformation TS 132 291 Section 6.1.6.2.2.7
type UserInformation struct {
	ServedGPSI          string        `json:"servedGPSI" yaml:"servedGPSI" bson:"servedGPSI" mapstructure:"ServedGPSI"`
	ServedPEI           string        `json:"servedPEI" yaml:"servedPEI" bson:"servedPEI" mapstructure:"ServedPEI"`
	UnauthenticatedFlag bool          `json:"unauthenticatedFlag" yaml:"unauthenticatedFlag" bson:"unauthenticatedFlag" mapstructure:"UnauthenticatedFlag"`
	RoamerInOut         []RoamerInOut `json:"roamerInOut" yaml:"roamerInOut" bson:"roamerInOut" mapstructure:"RoamerInOut"`
}
